app/chat/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[DataRequired()])
    room = StringField('Room', validators=[DataRequired()])
    submit = SubmitField('Enter Chatroom')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO
from secrets import token_hex
from flask_cors import CORS
from .videoManager import VideoManager, HmdManager,Hmd, VideoDevice
from flask_bootstrap import Bootstrap5


socketio = SocketIO(cors_allowed_origins='*')

videoManager:VideoManager = VideoManager()
hmdManager:HmdManager = HmdManager()



def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    # intentionally make old session expire on each rerun
    #app.config['SECRET_KEY'] = token_hex(32)
    app.config['SECRET_KEY'] ="7f7de268f92d245847e5265d5198deabe48f3a97deb26a8527b5c8eff05d51bf"
    CORS(app)
    Bootstrap5(app)

    from .main import main as main_bp
    app.register_blueprint(main_bp)
    from .chat import chat as chat_bp
    app.register_blueprint(chat_bp, url_prefix='/chat')

    socketio.init_app(app)
    return app

app/chat/__init__.py
from flask import Blueprint

chat = Blueprint('chat', __name__)

from . import routes, events

app/chat/routes.py
from flask import session, redirect, url_for, render_template, request
from . import chat
from .forms import LoginForm


@chat.route('/', methods=['GET', 'POST'])
def index():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('chat/index.html', form=form)


@chat.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('chat/chat.html', name=name, room=room)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import Response, send_from_directory, session, redirect, url_for, render_template, request
from . import main
from .. import videoManager, hmdManager
from ..camera_opencv import Camera


@main.route("/favicon.ico")
def fav():
    return send_from_directory("static", "favicon.ico")


@main.route("/script/<filename>")
def script(filename):
    return send_from_directory("script", filename)

@main.route("/video_devices")
def video_devices():
    return videoManager.to_dict()

@main.route("/get_hmds")
def get_hmds():
    ret = []
    for hmd in hmdManager.hmds:
        ret.append(hmd.to_dict())
    return ret


@main.route('/', methods=['GET'])
def index():
    return render_template("main/index.html")


@main.route('/video_source', methods=['GET'])
def video_source():
    return render_template("main/video_source.html")


@main.route('/admin', methods=['GET', 'POST'])
def admin():
    return render_template("main/admin.html")

@main.route('/camera')
def cameraPage():
    return render_template("main/camera.html")

def gen(camera:Camera):
    """Video streaming generator function."""
    yield b'--frame\r\n'
    while True:
        frame = camera.get_frame()
        yield b'Content-Type: image/png\r\n\r\n' + frame + b'\r\n--frame\r\n'

@main.route('/video_feed')
def video_feed():
    """Video streaming route. Put this in the src attribute of an img tag."""
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame',
                    headers={
                        'Content-Security-Policy': "default-src 'self'",
                        'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
                    })


@main.route('/capture', methods=['GET', 'POST'])
def capture():
    return render_template("main/capturetest.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
            <meta charset="utf-8" />
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="description" content="Reflection Video Delivery" />
        <meta name="keywords" content="Reflection, Video, Webrtc" />
            <meta name="viewport"
                  content="width=device-width, initial-scale=1, shrink-to-fit=no" />
            {% block styles %}
            {% endblock styles %}
            <title>
                {% block title %}
                {% endblock title %}
            - Reflections</title>
        {% endblock head %}
    </head>
    <body>
        {% block content %}
        {% endblock content %}
        {% block scripts %}
        <script src="https://cdn.socket.io/4.4.1/socket.io.min.js"
        integrity="sha384-fKnu0iswBIqkjxrhQCTZ7qlLHOFEgNkRmK2vaO/LbTZSXdJfAu6ewRBdwHPhBo/H"
        crossorigin="anonymous"></script>
        {% endblock scripts %}
    </body>
</html>

app/templates/chat/chat.html
{% extends "base.html" %}
{% block title %}
    Chat: {{ room }}
{% endblock title %}
{% block head %}
    {{ super() }}
{% endblock head %}
{% block content %}
    <h1>Flask-SocketIO-Chat: {{ room }}</h1>
    <textarea id="chat" cols="80" rows="20"></textarea>
    <br>
    <br>
    <input id="text" size="80" placeholder="Enter your message here">
    <br>
    <br>
    <a href="#" onclick="leave_room();">Leave this room</a>
{% endblock content %}
{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="//cdn.socket.io/4.4.1/socket.io.min.js"></script>
    <script type="text/javascript" charset="utf-8">
        var socket;
        $(document).ready(function(){
            socket = io.connect('wss://' + document.domain + ':' + location.port + '/chat');
            socket.on('connect', function() {
                socket.emit('joined', {});
            });
            socket.on('status', function(data) {
                $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });
            socket.on('message', function(data) {
                $('#chat').val($('#chat').val() + data.msg + '\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });
            $('#text').keypress(function(e) {
                var code = e.keyCode || e.which;
                if (code == 13) {
                    text = $('#text').val();
                    $('#text').val('');
                    socket.emit('text', {msg: text});
                }
            });
        });
        function leave_room() {
            socket.emit('left', {}, function() {
                socket.disconnect();

                // go back to the login page
                window.location.href = "{{ url_for('chat.index') }}";
            });
        }
    </script>
{% endblock scripts %}

app/templates/chat/index.html
{% extends "base.html" %}
{% block title %}
  Chat
{% endblock title %}
{% block head %}
  {{ super() }}
  
{% endblock head %}
{% block content %}
  <h1>Flask-SocketIO-Chat</h1>
        <form method="post">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
{% endblock content %}
{% block scripts %}
  {{ super() }}
  <script type="module">
    
  </script>
  
{% endblock scripts %}

app/templates/main/admin.html
{% extends "base.html" %}
{% block title %}
  Admin
{% endblock title %}
{% block head %}
  {{ super() }} {{ bootstrap.load_css() }}
{% endblock head %}
{% block content %}
  <div class="card">
    <div class="card-header">
      <form id="hmdSelectionForm">
        <ul class="nav nav-tabs card-header-tabs">
          <h5>Select HMD:</h5>
          <div id="hmdSelect"></div>
          <li class="nav-item ms-auto">
            <!-- TODO: refresh need to be refactored -->
            <a class="btn btn-sm btn-primary" onclick="window.location.reload()">Refresh ALL</a>
            <a class="btn btn-sm btn-primary" onclick="window.open('/video_source', '_blank')">Video Source</a>
            <a class="btn btn-sm btn-primary" onclick="window.open('/', '_blank')">HMD</a>
          </li>
        </ul>
      </form>
    </div>
    <div class="card-body" id="vidCards"></div>
  </div>
  {{ super() }}
{% endblock content %}
{% block scripts %}
  {{ super() }}
  <script type="module">

    import {
      prepareSocket,
      getConnectedDevices,
      playVideoFromCamera,
      playAllVideoInput,
    } from "/script/utils.js";

    window.socket = io("wss://" + window.location.host);
  
  function make_card(vid) {
    let card = document.createElement("div");
    card.classList.add("card", "d-inline-block", "m-1");
    card.style.width = "18rem";
    card.id = vid["id"];
    let img = document.createElement("img");
    img.src = vid["preview"];
    img.classList.add("card-img-top");
    card.appendChild(img);
    let cardBody = document.createElement("div");
    cardBody.classList.add("card-body");
    card.appendChild(cardBody);
    let card_text = document.createElement("p");
    card_text.classList.add("card-text");
    card_text.innerHTML = vid["description"];
    cardBody.appendChild(card_text);
    let buttonGroup = document.createElement("div");
    buttonGroup.classList.add("d-flex", "justify-content-between");
    cardBody.appendChild(buttonGroup);
    let project = document.createElement("a");
    project.classList.add("btn", "btn-danger", "me-auto");
    project.innerHTML = "Project";
    project.onclick = () => {
      const vidId = event.target.parentNode.parentNode.parentNode.id;
      const form = document.getElementById("hmdSelectionForm");
      socket.emit("projectOrder",{vidId:vidId,hmd:form.elements['hmd'].value});
    };
    buttonGroup.appendChild(project);
    let refresh = document.createElement("a");
    refresh.classList.add("btn", "btn-primary", "ms-auto");
    refresh.innerHTML = "Refresh";
    refresh.onclick = (event) => {
      const vidId = event.target.parentNode.parentNode.parentNode.id;
      socket.emit("refreshPreview", vidId);
    };
    buttonGroup.appendChild(refresh);
    return card;
  }
  function make_hmd_select(data) {
    const base = document.getElementById("hmdSelect");

    if (data.length > 0) {
      base.innerHTML = "";
      for (let i = 0; i < data.length; i++) {
        let name = data[i]["name"] ? data[i]["name"] : data[i]["id"];
        let hmdDiv = document.createElement("div");
        hmdDiv.classList.add("form-check", "form-check-inline");
        let input = document.createElement("input");
        input.classList.add("form-check-input");
        input.type = "radio";
        input.name = "hmd";
        input.id = "hmd" + i;
        input.value = data[i]["id"];
        hmdDiv.appendChild(input);
        let label = document.createElement("label");
        label.classList.add("form-check-label");
        label.htmlFor = "hmd" + i;
        label.innerHTML = name;
        hmdDiv.appendChild(label);
        base.appendChild(hmdDiv);
      }
      base.childNodes[0].childNodes[0].checked = true;
    } else {
      base.innerHTML = "No HMD connected";
    }
  }
  socket.on("admin joined", () => {
    fetch("/video_devices")
      .then((response) => response.json())
      .then((data) => {
        let vidCards = document.getElementById("vidCards");
        for (let device in data) {
          for (let vid of data[device]) {
            vidCards.appendChild(make_card(vid));
          }
        }
      });
    fetch("/get_hmds")
      .then((response) => response.json())
      .then((data) => {
        make_hmd_select(data);
      });
  });

  socket.on("admin rejected", () => {
    alert("Admin rejected");
    window.location.href = "/video_source";
  });

  socket.on("videoRefreshed", (data) => {
    for (let key in data) {
      const cardToUpdate = document.getElementById(key);
      cardToUpdate.children[0].src = data[key];
    }
  });

  socket.emit("registerAdmin");

  //document.getElementById("vidCards").appendChild(make_card());
  </script>
  {{ bootstrap.load_js() }}
{% endblock scripts %}

app/templates/main/camera.html
<html>
  <head>
    <title>Video Streaming Demonstration</title>
  </head>
  <body>
    <h1>Video Streaming Demonstration</h1>
    <img src="{{ url_for('main.video_feed') }}">
  </body>
</html>

app/templates/main/capturetest.html
{% extends "base.html" %}
{% block title %}
    HMD
{% endblock title %}
{% block head %}
    {{ super() }}
    <style>
#video {
border: 1px solid black;
box-shadow: 2px 2px 3px black;
width: 320px;
height: 240px;
}
#photo {
border: 1px solid black;
box-shadow: 2px 2px 3px black;
width: 320px;
height: 240px;
}
#canvas {
display: none;
}
.camera {
width: 340px;
display: inline-block;
}
.output {
width: 340px;
display: inline-block;
vertical-align: top;
}
#startbutton {
display: block;
position: relative;
margin-left: auto;
margin-right: auto;
bottom: 32px;
background-color: rgba(0, 150, 0, 0.5);
border: 1px solid rgba(255, 255, 255, 0.7);
box-shadow: 0px 0px 1px 2px rgba(0, 0, 0, 0.2);
font-size: 14px;
font-family: "Lucida Grande", "Arial", sans-serif;
color: rgba(255, 255, 255, 1);
}
.contentarea {
font-size: 16px;
font-family: "Lucida Grande", "Arial", sans-serif;
width: 760px;
}
    </style>
{% endblock head %}
{% block content %}
    <div class="contentarea">
        <h1>MDN - navigator.mediaDevices.getUserMedia(): Still photo capture demo</h1>
        <p>
            This example demonstrates how to set up a media stream using your built-in
            webcam, fetch an image from that stream, and create a PNG using that image.
        </p>
        <div class="camera">
            <video id="video">
                Video stream not available.
            </video>
            <button id="startbutton">Take photo</button>
        </div>
        <canvas id="canvas"> </canvas>
        <div class="output">
            <img id="photo" alt="The screen capture will appear in this box." />
        </div>
        <p>
            Visit our article
            <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos">
            Taking still photos with WebRTC</a>
            to learn more about the technologies used here.
        </p>
    </div>
{% endblock content %}
{% block scripts %}
    {{ super() }}
    <script type="module">
      import {prepareSocket} from '/script/utils.js';
      
      const socket = prepareSocket();
    </script>
    <script type="text/javascript">
        (() => {
            // The width and height of the captured photo. We will set the
            // width to the value defined here, but the height will be
            // calculated based on the aspect ratio of the input stream.
          
            const width = 320; // We will scale the photo width to this
            let height = 0; // This will be computed based on the input stream
          
            // |streaming| indicates whether or not we're currently streaming
            // video from the camera. Obviously, we start at false.
          
            let streaming = false;
          
            // The various HTML elements we need to configure or control. These
            // will be set by the startup() function.
          
            let video = null;
            let canvas = null;
            let photo = null;
            let startbutton = null;
          
            function showViewLiveResultButton() {
              if (window.self !== window.top) {
                // Ensure that if our document is in a frame, we get the user
                // to first open it in its own tab or window. Otherwise, it
                // won't be able to request permission for camera access.
                document.querySelector(".contentarea").remove();
                const button = document.createElement("button");
                button.textContent = "View live result of the example code above";
                document.body.append(button);
                button.addEventListener("click", () => window.open(location.href));
                return true;
              }
              return false;
            }
          
            function startup() {
              if (showViewLiveResultButton()) {
                return;
              }
              video = document.getElementById("video");
              canvas = document.getElementById("canvas");
              photo = document.getElementById("photo");
              startbutton = document.getElementById("startbutton");
          
              navigator.mediaDevices
                .getUserMedia({ video: true, audio: false })
                .then((stream) => {
                  video.srcObject = stream;
                  video.play();
                })
                .catch((err) => {
                  console.error(`An error occurred: ${err}`);
                });
          
              video.addEventListener(
                "canplay",
                (ev) => {
                  if (!streaming) {
                    height = video.videoHeight / (video.videoWidth / width);
          
                    // Firefox currently has a bug where the height can't be read from
                    // the video, so we will make assumptions if this happens.
          
                    if (isNaN(height)) {
                      height = width / (4 / 3);
                    }
          
                    video.setAttribute("width", width);
                    video.setAttribute("height", height);
                    canvas.setAttribute("width", width);
                    canvas.setAttribute("height", height);
                    streaming = true;
                  }
                },
                false
              );
          
              startbutton.addEventListener(
                "click",
                (ev) => {
                  takepicture();
                  ev.preventDefault();
                },
                false
              );
          
              clearphoto();
            }
          
            // Fill the photo with an indication that none has been
            // captured.
          
            function clearphoto() {
              const context = canvas.getContext("2d");
              context.fillStyle = "#AAA";
              context.fillRect(0, 0, canvas.width, canvas.height);
          
              const data = canvas.toDataURL("image/png");
              photo.setAttribute("src", data);
            }
          
            // Capture a photo by fetching the current contents of the video
            // and drawing it into a canvas, then converting that to a PNG
            // format data URL. By drawing it on an offscreen canvas and then
            // drawing that to the screen, we can change its size and/or apply
            // other changes before drawing it.
          
            function takepicture() {
              const context = canvas.getContext("2d");
              if (width && height) {
                canvas.width = width;
                canvas.height = height;
                context.drawImage(video, 0, 0, width, height);
          
                const data = canvas.toDataURL("image/png");
                photo.setAttribute("src", data);
              } else {
                clearphoto();
              }
            }
          
            // Set up our event listener to run the startup process
            // once loading is complete.
            window.addEventListener("load", startup, false);
          })();
          
    </script>
{% endblock scripts %}

app/templates/main/index.html
{% extends "base.html" %}
{% block title %}
  HMD
{% endblock title %}
{% block
  head %}
  {{ super() }}
{% endblock head %}
{% block content %}
{% endblock
content %}
{% block scripts %}
  {{ super() }}
  <script async
          src="https://unpkg.com/es-module-shims@1.6.3/dist/es-module-shims.js"></script>
  <script type="importmap">
  {
    "imports": {
      "three": "https://unpkg.com/three@0.152.2/build/three.module.js",
      "three/addons/": "https://unpkg.com/three@0.152.2/examples/jsm/"
    }
  }
  </script>
  <script type="module">
    import { VRButton } from 'three/addons/webxr/VRButton.js';

  const canvas = document.createElement('canvas');
  canvas.width = 640;
  canvas.height = 480;
  const context = canvas.getContext('2d');
  const img = new Image();

  //window.lastTime = Date.now();
  img.onload = function() {
  //let timediff = Date.now() - window.lastTime;
  //console.log(timediff);
  //window.lastTime = Date.now();
  context.drawImage(img, 0, 0);
    setTimeout(function() {
      img.src = '{{ url_for('main.video_feed') }}';
    }, 30);
  };
  img.src = '{{ url_for('main.video_feed') }}';

  import { Scene, PerspectiveCamera,WebGLRenderer,PlaneGeometry,CanvasTexture,MeshBasicMaterial,Mesh,DoubleSide } from "three";
  import { OrbitControls } from "three/addons/controls/OrbitControls.js";
  import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";

  const scene = new Scene();
  const camera = new PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

  const renderer = new WebGLRenderer();
  renderer.setSize( window.innerWidth, window.innerHeight );
  document.body.appendChild( renderer.domElement );
  const geometry = new PlaneGeometry( 0.64, 0.48);
  geometry.translate(0,-0.06,-0.6);

  const texture = new CanvasTexture(canvas);
  const material = new MeshBasicMaterial({map: texture,});
  //const material = new MeshBasicMaterial({color: 0xffff00, side: DoubleSide} );
  
  document.body.appendChild( VRButton.createButton( renderer ) );
  renderer.xr.enabled = true;

  const plane = new Mesh( geometry, material );

  scene.add( plane );

  //camera.position.z = 0.6;

  console.log(camera.position)
  console.log(camera.rotation)
  console.log(plane.position)
  console.log(plane.rotation)
  

  renderer.setAnimationLoop( function () {
    texture.needsUpdate = true;
    plane.position.set(camera.position.x,camera.position.y,camera.position.z);
    plane.rotation.set(camera.rotation.x,camera.rotation.y,camera.rotation.z);
    renderer.render( scene, camera );
  
  } );
  </script>
  <!--abandoned webrtc infrastructures-->
  <!--script type="module">
  const configuration = {
    iceServers: [{ urls: "stun:stun.l.google.com:19302" }],
  };
  const peerConnection = new RTCPeerConnection();

  window.socket = io("wss://" + window.location.host);

  peerConnection.addEventListener("icecandidate", (event) => {
    console.log(event.candidate);
    if (event.candidate) {
      socket.emit("roomMessage", { room: sessionStorage.getItem("room"), "new-ice-candidate": event.candidate });
    }
  });

  peerConnection.addEventListener('connectionstatechange', event => {
    if (peerConnection.connectionState === 'connected') {
        alert("p2p Connected");
    }
});

  socket.on("connect", () => {
    socket.emit("register_hmd");
  });

  socket.on("roomMessage", async (data) => {
    if (data.hasOwnProperty("offer")) {
      console.log(data['offer'])
      sessionStorage.setItem("room", data["room"]);
      peerConnection.setRemoteDescription(
        new RTCSessionDescription(data["offer"])
      );
      const answer = await peerConnection.createAnswer();
      await peerConnection.setLocalDescription(answer);
      socket.emit("roomMessage", { room: data["room"], answer: answer });
    } else if (data.hasOwnProperty("new-ice-candidate")) {
      console.log(data['new-ice-candidate'])
      try {
        await peerConnection.addIceCandidate(data['new-ice-candidate']);
    } catch (e) {
        console.error('Error adding received ice candidate', e);
    }
    }
  });
    </!--script-->
{% endblock scripts %}

app/templates/main/video_source.html
{% extends "base.html" %}
{% block title %}
  Video Source
{% endblock title %}
{%
block head %} {{ super() }}
{% endblock head %}
{% block content %}
  Video Source
  <div id="vidContainer"></div>
{% endblock content %}
{% block scripts %}
  {{ super() }}
  <script type="module">
    import {
      prepareSocket,
      getConnectedDevices,
      playVideoFromCamera,
      playAllVideoInput,
    } from "/script/utils.js";

    const configuration = {
      iceServers: [{ urls: "stun:stun.l.google.com:19302" }],
    };
    const peerConnection = new RTCPeerConnection();
    const offer = await peerConnection.createOffer();
    await peerConnection.setLocalDescription(offer);

    window.socket = io("wss://" + window.location.host);

    peerConnection.addEventListener("icecandidate", (event) => {
      console.log(event.candidate);
      if (event.candidate) {
        socket.emit("roomMessage", { room: sessionStorage.getItem("room"), "new-ice-candidate": event.candidate });
      }
    });

    peerConnection.addEventListener('connectionstatechange', event => {
      if (peerConnection.connectionState === 'connected') {
          alert("p2p Connected");
      }
  });

    socket.on("connect", async function () {
      const mediaDev = await getConnectedDevices("videoinput");
      if (mediaDev.length > 0) {
        let width = 200;
        let height = 150;
        let canvas = document.createElement("canvas");
        canvas.width = width;
        canvas.height = height;
        let video = document.createElement("video");
        let devices = await getConnectedDevices("videoinput");
        let ret = {};
        for (let i = 0; i < devices.length; i++) {
          video.srcObject = await navigator.mediaDevices.getUserMedia({
            video: { deviceId: devices[i].deviceId },
          });
          await video.play();
          let ctx = canvas.getContext("2d").drawImage(video, 0, 0, width, height);
          ret[devices[i].deviceId] = {
            label: devices[i].label,
            preview: canvas.toDataURL("image/jpeg", 0.3),
          };
          video.srcObject = null;
        }
        socket.emit("registerVidSource", ret);
        await playAllVideoInput(document.getElementById("vidContainer"));
      } else {
        document.getElementById("vidContainer").innerHTML = "No camera found";
      }
    });
    socket.on("refreshPreview", async function (vidId) {
      //TODO: handle null stream exception
      let stream = await navigator.mediaDevices.getUserMedia({
        video: { deviceId: vidId },
      });

      if (stream) {
        let width = 200;
        let height = 150;
        let canvas = document.createElement("canvas");
        canvas.width = width;
        canvas.height = height;
        let video = document.createElement("video");
        let ret = {};
        video.srcObject = stream;
        await video.play();
        let ctx = canvas.getContext("2d").drawImage(video, 0, 0, width, height);
        (ret[vidId] = canvas.toDataURL("image/jpeg", 0.3)),
          socket.emit("videoRefreshed", ret);
      }
    });
    socket.on("projectOrder", async (data) => {
      sessionStorage.setItem("room", data["room"]);
      socket.emit("roomMessage",{'room':data['room'],'offer':offer})
    });

    socket.on("roomMessage", async(data)=>{
      if(data.hasOwnProperty('answer')){
        console.log(data['answer'])
        const remoteDesc = new RTCSessionDescription(data['answer']);
        await peerConnection.setRemoteDescription(remoteDesc)
      }else if(data.hasOwnProperty('new-ice-candidate')){
        console.log(data['new-ice-candidate'])
        try {
          await peerConnection.addIceCandidate(data['new-ice-candidate']);
      } catch (e) {
          console.error('Error adding received ice candidate', e);
      }
      }




    });
  </script>
{% endblock scripts %}